### PR TITLE
Bypass Identity Tokens

### PR DESCRIPTION
**Pull request by MidSpike**
# Goals

- Trick the whitelist-system into not requiring Identity Tokens to operate

### CODE REVIEW

**Comment by MidSpike** [comment]
@dr4wn @rossloika @WillFJS @TotoTheEgg please review

**Review by rossloika — APPROVED** [review]
Looks good, did not see any noticible issues.

**Review by WillFJS — APPROVED** [review]

**Review by dr4wn — APPROVED** [review]

**Review by dr4wn — APPROVED** [review]
looks good

**Review by TotoTheEgg — APPROVED** [review]
A little worried about networking attacks / general security but I'm sure cloudflare can save our asses on that one

**Comment by MidSpike** [comment]
> A little worried about networking attacks / general security but I'm sure cloudflare can save our asses on that one

Security-wise we'll be alright, we'll just have to work on anti-(d)dos

**Comment by MidSpike** [comment]
This has been successfully tested

**Pull request merged**
