### PR TITLE
Added carousel for the products command

### PR DESCRIPTION
**Pull request by MidSpike**
Suggestion credit to user 326740893384179712
image

### CODE REVIEW

**Comment by MidSpike** [comment]
image

**Review by itsdrawn — APPROVED** [review]
lgtm

**Review by Will3126 — APPROVED** [review]
Looks good, I know for sure people were waiting on this feature, will take up less space in the channels.

**Comment by Will3126** [comment]
Are you going to add back the role mention or just leave it out?

**Review by rossloika — APPROVED** [review]

**Pull request merged**
