### PR TITLE
Removal of Discord Roles for Products

### LINKED ISSUE #158: Removal of Discord Roles for Products
# Problem
We need to remove the database syncing for all discord roles as our Discord Product Roles are deprecated and will be completely removed at a later date.

# Goals
- Remove all traces of discord roles in codebase

### PR DESCRIPTION
**Pull request by MidSpike**
Fixes #158

### CODE REVIEW

**Comment by MidSpike** [comment]
> Question, how will we grant the members hidden channels like the channel for all the keybinds

channels like that will not exist soon as I have merged all relevant information directly into the product readme

**Comment by MidSpike** [comment]
@dr4wn @WillFJS please review / approve

**Comment by MidSpike** [comment]
> @dr4wn @WillFJS please review / approve

@dr4wn @WillFJS follow-up ping

**Review by dr4wn — APPROVED** [review]
lgtm

**Pull request merged**
