### PR TITLE
add clarity to product purchase embed

### PR DESCRIPTION
**Pull request by itsdrawn**
not requesting MidSpike as he is on leave

### CODE REVIEW

**Review by Will3126 — CHANGES_REQUESTED** [review]
Line 175 at the end where you have download product and the "channel id" that is a role id not channel id their for it won't work. Also it's in a dm I believe so that also won't fit for the channel.

**Comment by itsdrawn** [comment]
> 
> 
> Line 175 at the end where you have download product and the "channel id" that is a role id not channel id their for it won't work. Also it's in a dm I believe so that also won't fit for the channel.

oh..i did not realize

you can mention channels from DMs, but is there any storage of our product channel id? @Will3126

**Comment by DevSighted** [comment]
you retard ffs

**Comment by Will3126** [comment]
> > 
> 
> > 
> 
> > Line 175 at the end where you have download product and the "channel id" that is a role id not channel id their for it won't work. Also it's in a dm I believe so that also won't fit for the channel.
> 
> 
> 
> oh..i did not realize
> 
> 
> 
> you can mention channels from DMs, but is there any storage of our product channel id? @Will3126 

Negative

**Comment by MidSpike** [comment]
> you can mention channels from DMs, but is there any storage of our product channel id? @Will3126

this is not true for all discord clients

**Pull request closed without merging**
