### PR TITLE
profile system

### PR DESCRIPTION
**Pull request by MidSpike**

### CODE REVIEW

**Review by TotoTheEgg — CHANGES_REQUESTED** [review]
Automated quick support handler:
 - Check if mentioning a channel (like #support) is what is triggering the support message, as there are several times where members mention the #support channel and automated support responds
 - add an auto delete after 3(?) minutes

user profile handler:
 - Add if user is blacklisted

**Comment by MidSpike** [comment]
> Automated quick support handler:
> 
> * Check if mentioning a channel (like #support) is what is triggering the support message, as there are several times where members mention the #support channel and automated support responds
> * add an auto delete after 3(?) minutes
> 
> user profile handler:
> 
> * Add if user is blacklisted

Added the user blacklisted part to user profiles, however the quick support system requests are out of scope for this PR

**Comment by TotoTheEgg** [comment]
> > Automated quick support handler:
> > 
> > * Check if mentioning a channel (like #support) is what is triggering the support message, as there are several times where members mention the #support channel and automated support responds
> > * add an auto delete after 3(?) minutes
> > 
> > user profile handler:
> > 
> > * Add if user is blacklisted
> 
> Added the user blacklisted part to user profiles, however the quick support system requests are out of scope for this PR

Thanks <3

**Review by TotoTheEgg — APPROVED** [review]

**Review by WillFJS — APPROVED** [review]

**Review by TotoTheEgg — APPROVED** [review]

**Review by rossloika — APPROVED** [review]

**Comment by MidSpike** [comment]
Testing has revealed bugs that were fixed.

**Pull request merged**
