### PR TITLE
added kick command

### PR DESCRIPTION
**Pull request by MidSpike**

### CODE REVIEW

**Review by rossloika — APPROVED** [review]

**Review by itsdrawn — APPROVED** [review]
looks good to me

**Review by Will3126 — APPROVED** [review]
All good!

**Comment by MidSpike** [comment]
don't merge without testing first

**Comment by Will3126** [comment]
Going to be testing this later today

**Comment by Will3126** [comment]
@MidSpike can you change the branch on the bot so we can test this as I forgot to yerserday.

**Pull request merged**
