### PR TITLE
Adds compatibility for all suggestions channels in the suggestions category

### PR DESCRIPTION
**Pull request by MidSpike**

### CODE REVIEW

**Comment by itsdrawn** [comment]
lgtm

**Review by itsdrawn — COMMENTED** [review]
refer to my original statement

**Comment by MidSpike** [comment]
@itsdrawn @rossloika still waiting for an approval

**Comment by itsdrawn** [comment]
> 
> 
> @itsdrawn @rossloika still waiting for an approval



> 
> 
> refer to my original statement

**Pull request merged**
